// <auto-generated />
using System;
using FirmPulse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FirmPulse.Data.Migrations
{
    [DbContext(typeof(FirmPulseDbContext))]
    partial class FirmPulseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FirmPulse.Entities.ClientFollowUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FollowUpDate")
                        .HasColumnType("date");

                    b.Property<string>("FollowUpType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("NextFollowUpDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("FirmId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ClientFollowUps");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("CompanyClass")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("FinancialYearEndDay")
                        .HasColumnType("integer");

                    b.Property<int?>("FinancialYearEndMonth")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasShareCapital")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("IncorporationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsListed")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastAGMDate")
                        .HasColumnType("date");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RegisteredOfficeAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("CompanyClients");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyCompliancePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AGMDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<int>("ComplianceTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("ComplianceTemplateId");

                    b.HasIndex("FirmId");

                    b.ToTable("CompanyCompliancePlans");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgendaPrepared")
                        .HasColumnType("boolean");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyCompliancePlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("MeetingDate")
                        .HasColumnType("date");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("MinutesPrepared")
                        .HasColumnType("boolean");

                    b.Property<bool>("NoticePrepared")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("SignedCopyReceived")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VenueOrMode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("CompanyCompliancePlanId");

                    b.HasIndex("FirmId");

                    b.ToTable("CompanyMeetings");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("ComplianceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("FirmId");

                    b.ToTable("ComplianceTasks");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("FinancialYearBased")
                        .HasColumnType("boolean");

                    b.Property<int?>("FirmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FirmId");

                    b.ToTable("ComplianceTemplates");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplianceTemplateId")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultDueOffsetDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DueDateBasedOn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("McaFormMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresDocuments")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresFiling")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresMeeting")
                        .HasColumnType("boolean");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceTemplateId");

                    b.HasIndex("McaFormMasterId");

                    b.HasIndex("ServiceMasterId");

                    b.ToTable("ComplianceTemplateItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PAN")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("ResignationDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.ToTable("Directors");
                });

            modelBuilder.Entity("FirmPulse.Entities.DocumentChecklistTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComplianceTemplateItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<int?>("ServiceMasterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceTemplateItemId");

                    b.HasIndex("ServiceMasterId");

                    b.ToTable("DocumentChecklistTemplates");
                });

            modelBuilder.Entity("FirmPulse.Entities.DocumentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplianceTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("FilingRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("ComplianceTaskId");

                    b.HasIndex("FilingRecordId");

                    b.HasIndex("FirmId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("DocumentRecords");
                });

            modelBuilder.Entity("FirmPulse.Entities.FilingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgementFilePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("ChallanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ChallanNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FilingDate")
                        .HasColumnType("date");

                    b.Property<string>("FinancialYear")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<int>("McaFormMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("McaStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SRN")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("FirmId");

                    b.HasIndex("McaFormMasterId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("FilingRecords");
                });

            modelBuilder.Entity("FirmPulse.Entities.Firm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("FirmPulse.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("FirmId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FirmPulse.Entities.McaFormMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicableTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultDueRule")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAnnualForm")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEventBasedForm")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("McaFormMasters");
                });

            modelBuilder.Entity("FirmPulse.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FirmPulse.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("FirmPulse.Entities.ServiceMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultDueDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DefaultFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("RecurringType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.ToTable("ServiceMasters");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ClientDocumentsStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CompanyCompliancePlanId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FilingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FinancialYear")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<int?>("McaFormMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("RequiresClientDocuments")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresMcaFiling")
                        .HasColumnType("boolean");

                    b.Property<int?>("ServiceMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("CompanyCompliancePlanId");

                    b.HasIndex("FirmId");

                    b.HasIndex("McaFormMasterId");

                    b.HasIndex("ServiceMasterId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItemDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("FirmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ReceivedDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly?>("ReviewedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("FirmId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("WorkItemDocuments");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItemStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId");

                    b.ToTable("WorkItemStatusHistories");
                });

            modelBuilder.Entity("FirmPulse.Entities.ClientFollowUp", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("ClientFollowUps")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.WorkItem", "WorkItem")
                        .WithMany("FollowUps")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyClient");

                    b.Navigation("Firm");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyClient", b =>
                {
                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany("CompanyClients")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyCompliancePlan", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("CompanyCompliancePlans")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.ComplianceTemplate", "ComplianceTemplate")
                        .WithMany("CompanyCompliancePlans")
                        .HasForeignKey("ComplianceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("ComplianceTemplate");

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyMeeting", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("CompanyMeetings")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.CompanyCompliancePlan", "CompanyCompliancePlan")
                        .WithMany("Meetings")
                        .HasForeignKey("CompanyCompliancePlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("CompanyCompliancePlan");

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTask", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("ComplianceTasks")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany("ComplianceTasks")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplate", b =>
                {
                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplateItem", b =>
                {
                    b.HasOne("FirmPulse.Entities.ComplianceTemplate", "ComplianceTemplate")
                        .WithMany("Items")
                        .HasForeignKey("ComplianceTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.McaFormMaster", "McaFormMaster")
                        .WithMany("ComplianceTemplateItems")
                        .HasForeignKey("McaFormMasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.ServiceMaster", "ServiceMaster")
                        .WithMany("ComplianceTemplateItems")
                        .HasForeignKey("ServiceMasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ComplianceTemplate");

                    b.Navigation("McaFormMaster");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("FirmPulse.Entities.Director", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("Directors")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyClient");
                });

            modelBuilder.Entity("FirmPulse.Entities.DocumentChecklistTemplate", b =>
                {
                    b.HasOne("FirmPulse.Entities.ComplianceTemplateItem", "ComplianceTemplateItem")
                        .WithMany("DocumentChecklistTemplates")
                        .HasForeignKey("ComplianceTemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.ServiceMaster", "ServiceMaster")
                        .WithMany("DocumentChecklistTemplates")
                        .HasForeignKey("ServiceMasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ComplianceTemplateItem");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("FirmPulse.Entities.DocumentRecord", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.ComplianceTask", "ComplianceTask")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("ComplianceTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FirmPulse.Entities.FilingRecord", "FilingRecord")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("FilingRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.WorkItem", "WorkItem")
                        .WithMany("DocumentRecords")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyClient");

                    b.Navigation("ComplianceTask");

                    b.Navigation("FilingRecord");

                    b.Navigation("Firm");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FirmPulse.Entities.FilingRecord", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("FilingRecords")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.McaFormMaster", "McaFormMaster")
                        .WithMany("FilingRecords")
                        .HasForeignKey("McaFormMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.WorkItem", "WorkItem")
                        .WithMany("FilingRecords")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyClient");

                    b.Navigation("Firm");

                    b.Navigation("McaFormMaster");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FirmPulse.Entities.Invoice", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany("Invoices")
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("FirmPulse.Entities.Payment", b =>
                {
                    b.HasOne("FirmPulse.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FirmPulse.Entities.ServiceMaster", b =>
                {
                    b.HasOne("FirmPulse.Entities.ServiceCategory", "ServiceCategory")
                        .WithMany("Services")
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceCategory");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItem", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("WorkItems")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.CompanyCompliancePlan", "CompanyCompliancePlan")
                        .WithMany("WorkItems")
                        .HasForeignKey("CompanyCompliancePlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.McaFormMaster", "McaFormMaster")
                        .WithMany("WorkItems")
                        .HasForeignKey("McaFormMasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FirmPulse.Entities.ServiceMaster", "ServiceMaster")
                        .WithMany("WorkItems")
                        .HasForeignKey("ServiceMasterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompanyClient");

                    b.Navigation("CompanyCompliancePlan");

                    b.Navigation("Firm");

                    b.Navigation("McaFormMaster");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItemDocument", b =>
                {
                    b.HasOne("FirmPulse.Entities.CompanyClient", "CompanyClient")
                        .WithMany("WorkItemDocuments")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.Firm", "Firm")
                        .WithMany()
                        .HasForeignKey("FirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FirmPulse.Entities.WorkItem", "WorkItem")
                        .WithMany("Documents")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("Firm");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItemStatusHistory", b =>
                {
                    b.HasOne("FirmPulse.Entities.WorkItem", "WorkItem")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyClient", b =>
                {
                    b.Navigation("ClientFollowUps");

                    b.Navigation("CompanyCompliancePlans");

                    b.Navigation("CompanyMeetings");

                    b.Navigation("ComplianceTasks");

                    b.Navigation("Directors");

                    b.Navigation("DocumentRecords");

                    b.Navigation("FilingRecords");

                    b.Navigation("Invoices");

                    b.Navigation("WorkItemDocuments");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.CompanyCompliancePlan", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTask", b =>
                {
                    b.Navigation("DocumentRecords");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplate", b =>
                {
                    b.Navigation("CompanyCompliancePlans");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("FirmPulse.Entities.ComplianceTemplateItem", b =>
                {
                    b.Navigation("DocumentChecklistTemplates");
                });

            modelBuilder.Entity("FirmPulse.Entities.FilingRecord", b =>
                {
                    b.Navigation("DocumentRecords");
                });

            modelBuilder.Entity("FirmPulse.Entities.Firm", b =>
                {
                    b.Navigation("CompanyClients");

                    b.Navigation("ComplianceTasks");

                    b.Navigation("DocumentRecords");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FirmPulse.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FirmPulse.Entities.McaFormMaster", b =>
                {
                    b.Navigation("ComplianceTemplateItems");

                    b.Navigation("FilingRecords");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("FirmPulse.Entities.ServiceMaster", b =>
                {
                    b.Navigation("ComplianceTemplateItems");

                    b.Navigation("DocumentChecklistTemplates");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("FirmPulse.Entities.WorkItem", b =>
                {
                    b.Navigation("DocumentRecords");

                    b.Navigation("Documents");

                    b.Navigation("FilingRecords");

                    b.Navigation("FollowUps");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
